# Generated by Django 4.2.16 on 2024-10-23 09:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('policy', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationType',
            fields=[
                ('code', models.CharField(db_column='ConfirmationTypeCode', max_length=3, primary_key=True, serialize=False)),
                ('confirmationtype', models.CharField(db_column='ConfirmationType', max_length=50)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblConfirmationTypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.SmallIntegerField(db_column='EducationId', primary_key=True, serialize=False)),
                ('education', models.CharField(db_column='Education', max_length=50)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblEducations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('extended_data', models.JSONField(blank=True, null=True)),
                ('id', models.AutoField(db_column='FamilyID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='FamilyUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('poverty', models.BooleanField(blank=True, db_column='Poverty', null=True)),
                ('address', models.CharField(blank=True, db_column='FamilyAddress', max_length=200, null=True)),
                ('is_offline', models.BooleanField(blank=True, db_column='isOffline', null=True)),
                ('ethnicity', models.CharField(blank=True, db_column='Ethnicity', max_length=1, null=True)),
                ('confirmation_no', models.CharField(blank=True, db_column='ConfirmationNo', max_length=12, null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
                ('confirmation_type', models.ForeignKey(blank=True, db_column='ConfirmationType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='families', to='insuree.confirmationtype')),
            ],
            options={
                'db_table': 'tblFamilies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FamilyType',
            fields=[
                ('code', models.CharField(db_column='FamilyTypeCode', max_length=2, primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='FamilyType', max_length=50)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblFamilyTypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=1, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=50, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=50, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblGender',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('code', models.CharField(db_column='IdentificationCode', max_length=1, primary_key=True, serialize=False)),
                ('identification_type', models.CharField(db_column='IdentificationTypes', max_length=50)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=50, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblIdentificationTypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Insuree',
            fields=[
                ('version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('extended_data', models.JSONField(blank=True, null=True)),
                ('id', models.AutoField(db_column='InsureeID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='InsureeUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('chf_id', models.CharField(blank=True, db_column='CHFID', max_length=13, null=True)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('other_names', models.CharField(db_column='OtherNames', max_length=100)),
                ('arab_last_name', models.CharField(blank=True, db_column='ArabLastName', max_length=100, null=True)),
                ('arab_other_names', models.CharField(blank=True, db_column='ArabOtherNames', max_length=100, null=True)),
                ('dob', models.DateField(db_column='DOB')),
                ('head', models.BooleanField(db_column='IsHead')),
                ('marital', models.CharField(blank=True, db_column='Marital', max_length=1, null=True)),
                ('passport', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('current_address', models.CharField(blank=True, db_column='CurrentAddress', max_length=200, null=True)),
                ('geolocation', models.CharField(blank=True, db_column='GeoLocation', max_length=250, null=True)),
                ('photo_date', models.DateField(blank=True, db_column='PhotoDate', null=True)),
                ('card_issued', models.BooleanField(db_column='CardIssued')),
                ('offline', models.BooleanField(blank=True, db_column='isOffline', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
                ('current_village', models.ForeignKey(blank=True, db_column='CurrentVillage', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location')),
                ('education', models.ForeignKey(blank=True, db_column='Education', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.education')),
                ('family', models.ForeignKey(blank=True, db_column='FamilyID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='insuree.family')),
                ('gender', models.ForeignKey(blank=True, db_column='Gender', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.gender')),
                ('health_facility', models.ForeignKey(blank=True, db_column='HFID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='location.healthfacility')),
            ],
            options={
                'db_table': 'tblInsuree',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MembershipGroup',
            fields=[
                ('idMembershipgroup', models.AutoField(db_column='idMembershipGroup', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=250, null=True)),
            ],
            options={
                'db_table': 'tblMembershipGroup',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.SmallIntegerField(db_column='ProfessionId', primary_key=True, serialize=False)),
                ('profession', models.CharField(db_column='Profession', max_length=50)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblProfessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.SmallIntegerField(db_column='RelationId', primary_key=True, serialize=False)),
                ('relation', models.CharField(db_column='Relation', max_length=50)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblRelations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PolicyRenewalDetail',
            fields=[
                ('version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(db_column='RenewalDetailID', primary_key=True, serialize=False)),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditCreateUser', null=True)),
                ('insuree', models.ForeignKey(db_column='InsureeID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_renewal_details', to='insuree.insuree')),
                ('policy_renewal', models.ForeignKey(db_column='RenewalID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='policy.policyrenewal')),
            ],
            options={
                'db_table': 'tblPolicyRenewalDetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InsureePolicy',
            fields=[
                ('version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(db_column='InsureePolicyID', primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(blank=True, db_column='EnrollmentDate', null=True)),
                ('start_date', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('effective_date', models.DateField(blank=True, db_column='EffectiveDate', null=True)),
                ('expiry_date', models.DateField(blank=True, db_column='ExpiryDate', null=True)),
                ('offline', models.BooleanField(blank=True, db_column='isOffline', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
                ('insuree', models.ForeignKey(db_column='InsureeID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='insuree_policies', to='insuree.insuree')),
                ('policy', models.ForeignKey(db_column='PolicyId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='insuree_policies', to='policy.policy')),
            ],
            options={
                'db_table': 'tblInsureePolicy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InsureePhoto',
            fields=[
                ('version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(db_column='PhotoID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='PhotoUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('chf_id', models.CharField(blank=True, db_column='CHFID', max_length=13, null=True)),
                ('folder', models.CharField(blank=True, db_column='PhotoFolder', max_length=255, null=True)),
                ('filename', models.CharField(blank=True, db_column='PhotoFileName', max_length=250, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('officer_id', models.IntegerField(db_column='OfficerID')),
                ('date', models.DateField(db_column='PhotoDate')),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserID', null=True)),
                ('insuree', models.ForeignKey(blank=True, db_column='InsureeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photos', to='insuree.insuree')),
            ],
            options={
                'db_table': 'tblPhotos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InsureeMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mutation_date', models.DateTimeField(auto_now_add=True)),
                ('mutation_user_id', models.IntegerField()),
                ('insuree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='insuree.insuree')),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='core.mutationlog')),
            ],
            options={
                'db_table': 'insuree_InsureeMutation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InsureeAttachment',
            fields=[
                ('idAttachment', models.AutoField(db_column='idAttachment', primary_key=True, serialize=False)),
                ('folder', models.CharField(db_column='Folder', max_length=250, null=True)),
                ('filename', models.CharField(db_column='FileName', max_length=250, null=True)),
                ('title', models.CharField(db_column='Title', max_length=250, null=True)),
                ('date', models.DateField(blank=True, db_column='AttachmentDate', null=True)),
                ('document', models.TextField()),
                ('mime', models.CharField(db_column='Mime', max_length=250)),
                ('insuree', models.ForeignKey(db_column='InsureeID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='insuree.insuree')),
            ],
            options={
                'db_table': 'tblattachment',
            },
        ),
        migrations.AddField(
            model_name='insuree',
            name='membershipgroup',
            field=models.ForeignKey(blank=True, db_column='MembershipGroupID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.membershipgroup'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='photo',
            field=models.OneToOneField(blank=True, db_column='PhotoID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='insuree.insureephoto'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='profession',
            field=models.ForeignKey(blank=True, db_column='Profession', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.profession'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='relationship',
            field=models.ForeignKey(blank=True, db_column='Relationship', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.relation'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='type_of_id',
            field=models.ForeignKey(blank=True, db_column='TypeOfId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.identificationtype'),
        ),
        migrations.CreateModel(
            name='FamilyMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mutation_date', models.DateTimeField(auto_now_add=True)),
                ('mutation_user_id', models.IntegerField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='insuree.family')),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='families', to='core.mutationlog')),
            ],
            options={
                'db_table': 'insuree_FamilyMutation',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='family',
            name='family_type',
            field=models.ForeignKey(blank=True, db_column='FamilyType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='families', to='insuree.familytype'),
        ),
        migrations.AddField(
            model_name='family',
            name='head_insuree',
            field=models.OneToOneField(db_column='InsureeID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='head_of', to='insuree.insuree'),
        ),
        migrations.AddField(
            model_name='family',
            name='location',
            field=models.ForeignKey(blank=True, db_column='LocationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location'),
        ),
    ]
