# Generated by Django 4.2.16 on 2024-10-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='date_signature',
            field=models.DateField(db_column='DateSignature', null=True),
        ),
    ]
