# Generated by Django 4.2.16 on 2024-10-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0002_family_date_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='date_signature',
            field=models.DateField(db_column='DateSignature', null=True),
        ),
    ]
