# Generated by Django 4.2.16 on 2024-10-22 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(db_column='PolicyID', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('policy_number', models.CharField(db_column='PolicyNumber', max_length=50, unique=True)),
                ('start_date', models.DateField(db_column='StartDate')),
                ('expiry_date', models.DateField(blank=True, db_column='ExpiryDate', null=True)),
                ('status', models.CharField(db_column='Status', max_length=10)),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserID', null=True)),
            ],
            options={
                'db_table': 'tblPolicies',
            },
        ),
        migrations.CreateModel(
            name='PolicyRenewal',
            fields=[
                ('id', models.AutoField(db_column='RenewalID', primary_key=True, serialize=False)),
                ('renewal_date', models.DateField(db_column='RenewalDate')),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserID', null=True)),
                ('policy', models.ForeignKey(db_column='PolicyID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='renewals', to='policy.policy')),
            ],
            options={
                'db_table': 'tblPolicyRenewals',
            },
        ),
    ]
